### ISSUE TITLE
Accuracy Testing?

### ISSUE THREAD

**Issue by domierosina** [haoliangyu/pymasker#8]
Please opt to delete this (or I can come back and do so) I was just hoping there would be some information on accuracy of this product?

**Comment by haoliangyu** [comment]
Sorry, the link in the README is broken. For any information about the underline methodology, please check the product guide from USGS: https://www.usgs.gov/core-science-systems/nli/landsat/landsat-8-surface-reflectance-quality-assessment?qt-science_support_page_related_con=1#qt-science_support_page_related_con.

It has been a lot time since I worked on this. And I cannot remember the detail.
